// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: krate.proto

package kratev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LimitKey      string                 `protobuf:"bytes,1,opt,name=limit_key,json=limitKey,proto3" json:"limit_key,omitempty"`
	Requested     uint64                 `protobuf:"varint,2,opt,name=requested,proto3" json:"requested,omitempty"`
	OriginId      string                 `protobuf:"bytes,3,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_krate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_krate_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetLimitKey() string {
	if x != nil {
		return x.LimitKey
	}
	return ""
}

func (x *TransferRequest) GetRequested() uint64 {
	if x != nil {
		return x.Requested
	}
	return 0
}

func (x *TransferRequest) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       uint64                 `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_krate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_krate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_krate_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetGranted() uint64 {
	if x != nil {
		return x.Granted
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_krate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_krate_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_krate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_krate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_krate_proto_rawDescGZIP(), []int{3}
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginId      string                 `protobuf:"bytes,1,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Consumed      map[string]uint64      `protobuf:"bytes,2,rep,name=consumed,proto3" json:"consumed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Borrowed      map[string]uint64      `protobuf:"bytes,3,rep,name=borrowed,proto3" json:"borrowed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_krate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_krate_proto_rawDescGZIP(), []int{4}
}

func (x *GossipRequest) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *GossipRequest) GetConsumed() map[string]uint64 {
	if x != nil {
		return x.Consumed
	}
	return nil
}

func (x *GossipRequest) GetBorrowed() map[string]uint64 {
	if x != nil {
		return x.Borrowed
	}
	return nil
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_krate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_krate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_krate_proto_rawDescGZIP(), []int{5}
}

var File_krate_proto protoreflect.FileDescriptor

const file_krate_proto_rawDesc = "" +
	"\n" +
	"\vkrate.proto\x12\bkrate.v1\"i\n" +
	"\x0fTransferRequest\x12\x1b\n" +
	"\tlimit_key\x18\x01 \x01(\tR\blimitKey\x12\x1c\n" +
	"\trequested\x18\x02 \x01(\x04R\trequested\x12\x1b\n" +
	"\torigin_id\x18\x03 \x01(\tR\boriginId\",\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\x04R\agranted\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\xac\x02\n" +
	"\rGossipRequest\x12\x1b\n" +
	"\torigin_id\x18\x01 \x01(\tR\boriginId\x12A\n" +
	"\bconsumed\x18\x02 \x03(\v2%.krate.v1.GossipRequest.ConsumedEntryR\bconsumed\x12A\n" +
	"\bborrowed\x18\x03 \x03(\v2%.krate.v1.GossipRequest.BorrowedEntryR\bborrowed\x1a;\n" +
	"\rConsumedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a;\n" +
	"\rBorrowedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x10\n" +
	"\x0eGossipResponse2\xcf\x01\n" +
	"\x10KratePeerService\x12G\n" +
	"\x0eTransferTokens\x12\x19.krate.v1.TransferRequest\x1a\x1a.krate.v1.TransferResponse\x125\n" +
	"\x04Ping\x12\x15.krate.v1.PingRequest\x1a\x16.krate.v1.PingResponse\x12;\n" +
	"\x06Gossip\x12\x17.krate.v1.GossipRequest\x1a\x18.krate.v1.GossipResponseB\x8e\x01\n" +
	"\fcom.krate.v1B\n" +
	"KrateProtoP\x01Z1github.com/krigsherre/krate/internal/peer;kratev1\xa2\x02\x03KXX\xaa\x02\bKrate.V1\xca\x02\bKrate\\V1\xe2\x02\x14Krate\\V1\\GPBMetadata\xea\x02\tKrate::V1b\x06proto3"

var (
	file_krate_proto_rawDescOnce sync.Once
	file_krate_proto_rawDescData []byte
)

func file_krate_proto_rawDescGZIP() []byte {
	file_krate_proto_rawDescOnce.Do(func() {
		file_krate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_krate_proto_rawDesc), len(file_krate_proto_rawDesc)))
	})
	return file_krate_proto_rawDescData
}

var file_krate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_krate_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: krate.v1.TransferRequest
	(*TransferResponse)(nil), // 1: krate.v1.TransferResponse
	(*PingRequest)(nil),      // 2: krate.v1.PingRequest
	(*PingResponse)(nil),     // 3: krate.v1.PingResponse
	(*GossipRequest)(nil),    // 4: krate.v1.GossipRequest
	(*GossipResponse)(nil),   // 5: krate.v1.GossipResponse
	nil,                      // 6: krate.v1.GossipRequest.ConsumedEntry
	nil,                      // 7: krate.v1.GossipRequest.BorrowedEntry
}
var file_krate_proto_depIdxs = []int32{
	6, // 0: krate.v1.GossipRequest.consumed:type_name -> krate.v1.GossipRequest.ConsumedEntry
	7, // 1: krate.v1.GossipRequest.borrowed:type_name -> krate.v1.GossipRequest.BorrowedEntry
	0, // 2: krate.v1.KratePeerService.TransferTokens:input_type -> krate.v1.TransferRequest
	2, // 3: krate.v1.KratePeerService.Ping:input_type -> krate.v1.PingRequest
	4, // 4: krate.v1.KratePeerService.Gossip:input_type -> krate.v1.GossipRequest
	1, // 5: krate.v1.KratePeerService.TransferTokens:output_type -> krate.v1.TransferResponse
	3, // 6: krate.v1.KratePeerService.Ping:output_type -> krate.v1.PingResponse
	5, // 7: krate.v1.KratePeerService.Gossip:output_type -> krate.v1.GossipResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_krate_proto_init() }
func file_krate_proto_init() {
	if File_krate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_krate_proto_rawDesc), len(file_krate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_krate_proto_goTypes,
		DependencyIndexes: file_krate_proto_depIdxs,
		MessageInfos:      file_krate_proto_msgTypes,
	}.Build()
	File_krate_proto = out.File
	file_krate_proto_goTypes = nil
	file_krate_proto_depIdxs = nil
}
