// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: krate.proto

package kratev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KratePeerService_TransferTokens_FullMethodName = "/krate.v1.KratePeerService/TransferTokens"
	KratePeerService_Ping_FullMethodName           = "/krate.v1.KratePeerService/Ping"
	KratePeerService_Gossip_FullMethodName         = "/krate.v1.KratePeerService/Gossip"
)

// KratePeerServiceClient is the client API for KratePeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KratePeerServiceClient interface {
	TransferTokens(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Gossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error)
}

type kratePeerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKratePeerServiceClient(cc grpc.ClientConnInterface) KratePeerServiceClient {
	return &kratePeerServiceClient{cc}
}

func (c *kratePeerServiceClient) TransferTokens(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, KratePeerService_TransferTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kratePeerServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, KratePeerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kratePeerServiceClient) Gossip(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, KratePeerService_Gossip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KratePeerServiceServer is the server API for KratePeerService service.
// All implementations must embed UnimplementedKratePeerServiceServer
// for forward compatibility.
type KratePeerServiceServer interface {
	TransferTokens(context.Context, *TransferRequest) (*TransferResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Gossip(context.Context, *GossipRequest) (*GossipResponse, error)
	mustEmbedUnimplementedKratePeerServiceServer()
}

// UnimplementedKratePeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKratePeerServiceServer struct{}

func (UnimplementedKratePeerServiceServer) TransferTokens(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferTokens not implemented")
}
func (UnimplementedKratePeerServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedKratePeerServiceServer) Gossip(context.Context, *GossipRequest) (*GossipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedKratePeerServiceServer) mustEmbedUnimplementedKratePeerServiceServer() {}
func (UnimplementedKratePeerServiceServer) testEmbeddedByValue()                          {}

// UnsafeKratePeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KratePeerServiceServer will
// result in compilation errors.
type UnsafeKratePeerServiceServer interface {
	mustEmbedUnimplementedKratePeerServiceServer()
}

func RegisterKratePeerServiceServer(s grpc.ServiceRegistrar, srv KratePeerServiceServer) {
	// If the following call panics, it indicates UnimplementedKratePeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KratePeerService_ServiceDesc, srv)
}

func _KratePeerService_TransferTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KratePeerServiceServer).TransferTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KratePeerService_TransferTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KratePeerServiceServer).TransferTokens(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KratePeerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KratePeerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KratePeerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KratePeerServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KratePeerService_Gossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KratePeerServiceServer).Gossip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KratePeerService_Gossip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KratePeerServiceServer).Gossip(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KratePeerService_ServiceDesc is the grpc.ServiceDesc for KratePeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KratePeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "krate.v1.KratePeerService",
	HandlerType: (*KratePeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferTokens",
			Handler:    _KratePeerService_TransferTokens_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _KratePeerService_Ping_Handler,
		},
		{
			MethodName: "Gossip",
			Handler:    _KratePeerService_Gossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "krate.proto",
}
